gameControllerAddress: "224.5.23.1"
gameControllerDetectionPort: 10003

visionAddress: "224.5.23.2"
visionDetectionPort: 10020

simulationCommandAddress: "localhost"
simulationCommandPort: 10300

simulationRobotControlAddressBlue: "localhost"
simulationRobotControlPortBlue: 10301
simulationRobotControlAddressYellow: "localhost"
simulationRobotControlPortYellow: 10302

tritonBotAddressBlue: "192.168.22.74"
tritonBotPortBaseBlue: 10500
tritonBotAddressYellow: "192.168.22.74"
tritonBotPortBaseYellow: 10600
tritonBotPortIncr: 10